package com.kurume_nct.shogyomujo

import net.minecraft.entity.monster.EntityCreeper
import net.minecraftforge.common.MinecraftForge
import net.minecraftforge.fml.common.Mod
import net.minecraftforge.fml.common.Mod.EventHandler
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent

@Mod(modid = ShogyomujoMod.MODID, version = ShogyomujoMod.VERSION)
class ShogyomujoMod {

    @EventHandler
    fun preInit(event: FMLPreInitializationEvent) {
        MinecraftForge.EVENT_BUS.register(ExplosionEventHandler())
        MinecraftForge.EVENT_BUS.register(WorldEventHandler())
    }

    companion object {
        const val MODID = "shogyomujo"
        const val VERSION = "1.0"
        const val MOB_TAG = "generated by shogyomujo"
    }
}

var EntityCreeper.hasArrows: Boolean
    get() = ShogyomujoMod.MOB_TAG in tags
    set(value) {
        if (!value) return
        tags.add(ShogyomujoMod.MOB_TAG)
    }